// Public e-commerce metadata preview. Limited to known retail domains to avoid
// arbitrary server-side URL fetching. Site protections can still prevent previews.
const allowed = ['myntra.com','ajio.com','hm.com','zara.com','uniqlo.com','amazon.in','amazon.com','flipkart.com','meesho.com','adidas.co.in','nike.com','snitch.co.in','westside.com','tatacliq.com','nykaafashion.com','marksandspencer.in','bewakoof.com','thebearhouse.com','urbanic.com','souledstore.com','www2.hm.com'];
const matchDomain = host => allowed.some(d => host === d || host.endsWith('.'+d));
const privateHost = host => host === 'localhost' || host.endsWith('.local') || /^\d+(\.\d+){3}$/.test(host) || host.includes(':') || host.endsWith('.internal');
const decode = s => s?.replace(/&(?:amp|quot|apos|lt|gt|#39|#x27|#x2F);/g, x => ({'&amp;':'&','&quot;':'"','&apos;':"'",'&lt;':'<','&gt;':'>','&#39;':"'",'&#x27;':"'",'&#x2F;':'/'}[x]||x)).replace(/\s+/g,' ').trim() || '';
function meta(html,key){const tags = html.match(/<meta\b[^>]*>/gi) || [];for(const tag of tags){const attrs={};for(const m of tag.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g))attrs[m[1].toLowerCase()]=m[2]??m[3]??m[4];if([attrs.property,attrs.name].includes(key))return decode(attrs.content)}return ''}
exports.handler=async event=>{
 const headers={'content-type':'application/json; charset=utf-8','cache-control':'public,max-age=900'};
 try{const raw=event.queryStringParameters?.url;if(!raw||raw.length>2500)return {statusCode:400,headers,body:JSON.stringify({error:'Invalid link'})};const url=new URL(raw);if(url.protocol!=='https:'||privateHost(url.hostname)||!matchDomain(url.hostname))return {statusCode:422,headers,body:JSON.stringify({error:'Store not supported for previews; the link can still be saved'})};
 let target=url;let result;for(let i=0;i<3;i++){result=await fetch(target,{redirect:'manual',signal:AbortSignal.timeout(6500),headers:{'user-agent':'Mozilla/5.0 (compatible; WardrobeLinkPreview/1.0)','accept':'text/html'}});if(result.status>=300&&result.status<400){target=new URL(result.headers.get('location')||'',target);if(target.protocol!=='https:'||privateHost(target.hostname)||!matchDomain(target.hostname))throw Error('Unsafe redirect');continue}break}
 if(!result?.ok||!result.headers.get('content-type')?.includes('text/html'))throw Error('Shop did not provide page metadata');const reader=result.body.getReader();let chunks=[],length=0;while(length<260000){const {done,value}=await reader.read();if(done)break;chunks.push(value);length+=value.length}await reader.cancel();const html=new TextDecoder().decode(Buffer.concat(chunks.map(x=>Buffer.from(x))));
 const title=meta(html,'og:title')||meta(html,'twitter:title')||decode(html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1]||'');let img=meta(html,'og:image')||meta(html,'twitter:image');if(img){try{img=new URL(img,target).href;if(!img.startsWith('https://'))img=''}catch{img=''}}let price=meta(html,'product:price:amount')||meta(html,'og:price:amount')||meta(html,'twitter:data1');const currency=meta(html,'product:price:currency')||meta(html,'og:price:currency');if(price&&currency)price=currency+' '+price;
 return {statusCode:200,headers,body:JSON.stringify({title:title.slice(0,120),image:img,price:price.slice(0,45),vendor:target.hostname.replace(/^www\./,'')})};
 }catch(error){return {statusCode:502,headers,body:JSON.stringify({error:'Product preview unavailable; the link can still be saved'})}}
};
